version: '3'

services:
    proxy:
      build:
        context: ./docker/
      ports: "8085:8085"
      environment:
        XMRWASP_WSPORT: 8085
        XMRWASP_LOGIN: 47sfBPDL9qbDuF5stdrE8C6gVQXf15SeTN4BNxBZ3Ahs6LTayo2Kia2YES7MeN5FU7MKUrWAYPhmeFUYQ3v4JBAvKSPjigi
        XMRWASP_PASSWORD: x

    httpd:
        image: httpd:2.4
        ports: "80:80"
        logging:
            options:
                max-size: "50"

