version: '3'

services:
    proxy:
      build:
        context: ../
      ports:
        - "8085:8085"
      environment:
        XMRWASP_WSPORT: 8085
        XMRWASP_URL: xmrpool.eu:3333
        XMRWASP_LOGIN: 47sfBPDL9qbDuF5stdrE8C6gVQXf15SeTN4BNxBZ3Ahs6LTayo2Kia2YES7MeN5FU7MKUrWAYPhmeFUYQ3v4JBAvKSPjigi+docker
        XMRWASP_PASSWORD: x
        XMRWASP_DEBUG: true

    httpd:
        image: httpd:2.4
        ports:
          - "80:80"
        volumes:
          - ./:/usr/local/apache2/htdocs
        logging:
            options:
                max-size: "50"

